'''
    columns for deleting and adding
'''
cols_to_stay=[
        'url',
        'img',
        'product code',
        'model',
        'Part Number',
        'Brand',
        'Model name',
        'Display diagonal',
        'Release Date',
        'Form factor',
        'Internal memory',
        'Maximum internal memory',
        'Maximum internal memory (64-bit)',
        'Total storage capacity',
        'Storage media',
        'Processor family',
        'Processor model',
        'Depth',
        'Width',
        'Height',
        'Numeric keypad',
        'On-board graphics adapter',
        'Processor cores',
        'On-board graphics adapter model',
        'Operating system installed',
        'Front camera',
        'Processor cache',
        'Internal memory type',
        'Bluetooth',
        'Discrete graphics adapter',
        'Display resolution',
        'Wi-Fi standards',
        'Pointing device',
        'Discrete graphics adapter model',
        'Weight',
        'Built-in microphone',
        'Card reader integrated',
        'Processor frequency',
        'Touchscreen',
        'Ethernet LAN',
        'Processor boost frequency',
        'Family',
        'Product colour',
        'HD type',
        'LED backlight',
        'HDMI ports quantity',
        'Combo headphone/mic port',
        'AC adapter power',
        'Number of SSDs installed',
        'Bluetooth version',
        'SSD capacity',
        'Total SSDs capacity',
        'Operating system architecture',
        'Wi-Fi',
        'Memory clock speed',
        'Processor threads',
        'Processor lithography',
        'Cable lock slot',
        'Ethernet LAN data rates',
        'On-board graphics adapter base frequency',
        'Battery capacity (Watt-hours)',
        'Battery capacity (Watt hours)',
        'Battery capacity',
        'Password protection',
        'Front camera HD type',
        'Processor socket',
        'Speaker power',
        'Processor manufacturer',
        'Maximum on-board graphics adapter memory',
        'Keyboard backlit',
        'Panel type',
        'USB 3.2 Gen 1 (3.1 Gen 1) Type-A ports quantity',
        'USB 3.2 Gen 2 (3.1 Gen 2) Type-A ports quantity',
        'USB 3.0 (3.1 Gen 1) Type-A ports quantity',
        'USB 3.1 (3.1 Gen 2) Type-A ports quantity',
        'USB 3.2 (Gen 1) Type-A ports quantity',
        'USB 3.2 (Gen 2) Type-A ports quantity',
        'USB 3.2 Gen 2 (3.1 Gen 2) Type-C ports quantity',
        'USB 3.2 Gen 1 (3.1 Gen 1) Type-C ports quantity',
        'USB 3.0 (3.1 Gen 1) Type-C ports quantity',
        'USB 3.1 (3.1 Gen 2) Type-C ports quantity',
        'USB 3.2 Gen 2x2 Type-C ports quantity',
        'USB 3.2 (Gen 1) Type-C ports quantity',
        'USB Type-C Thunderbolt 3 ports quantity',
        'USB 2.0 ports quantity',
        'USB 2.0 Type-C ports quantity',
        'USB Sleep-and-Charge',
        'Front camera resolution',
        'Discrete graphics adapter memory',
        '4G',
        '3G',
        'Fingerprint reader',
        'Battery life (max)',
        'Discrete graphics memory type',
        'SSD form factor',
        'Trusted Platform Module (TPM)',
        'Password protection type',
        'Market positioning',
        'Front camera resolution (numeric)',
        'Audio chip',
        'Dual-screen',
        'Full-size keyboard',
        'Maximum refresh rate',
        'HDD capacity',
        'Docking connector',
        'DVI port',
        ]    

cols_to_add=[
    # NOTE: if 'cat' is not set then it is taken the same as for property in 'after' 
#    {'after':'Processor model', 'name': 'Processor (link)','cat': 'Processor'},
    {'after':'Processor model', 'name': 'Processor (link)'},
    {'after':'Discrete graphics adapter model', 'name': 'Discrete graphics adapter model (link)'},
    {'after':'USB 3.2 Gen 1 (3.1 Gen 1) Type-A ports quantity', 'name': 'USB 3.x Type-A ports'},
    {'after':'USB 3.2 Gen 2 (3.1 Gen 2) Type-C ports quantity', 'name': 'USB 3.x Type-C ports'},
    
    ]

cols_to_remane={
    'USB Type-C Thunderbolt 3 ports quantity': 'USB Type-C Thunderbolt 3 ports',
    'USB 2.0 Type-C ports quantity': 'USB 2.0 Type-C ports',
    'USB 2.0 ports quantity': 'USB 2.0 ports',
    }
